export default [
  "News you don't need to trust.",
  'Beyond trustworthy.',
  'Content for contents sake.',
  'Be content, not content',
  'The exit chute of The Butterfly Effect',
  'The content equivalent of carbs',
  'Your life. Our ad views.',
  'Too big for our news boots',
  'New media means new standards of journalism',
  'Writing things for you to read',
  'Making a short story long',
  'Breaking News',
  'Finger clickin’ good',
  'A blessing in a really good disguise',
  'To duplicity and beyond',
  'Post-truth, pre-fact',
];
